### ISSUE TITLE
Comments can have pointers to article content

### ISSUE THREAD

**Issue by simen** [VegaPublish/vega#11]
* Way to mark content in article then insert pointer in comment
* Way to "follow pointer" to the content in question

**Comment by simen** [comment]
Specification:

## When no comment is currently being written

When editing an article, every addressable item in the form builder gets a discrete vertical three-dot symbol (⋮) in the left margin. 

Addressable items include every field, every paragraph and embed in block text, every array item.

When clicking the three dot symbol the user is presented with a context menu with two options:

- [icon] Copy item link
- [icon] Comment

The first option copies a link to this item to the clipboard.

The second option starts a new comment starting with a reference to the item.

## When a comment is being written

When a comment is being written, the three-dot menu is transformed into the icon representing the "comment" options. When this icon is clicked, a reference to the corresponding item is added to the current comment.

**Comment by thomax** [comment]
This is quite a high-level issue, most of which is specified here https://github.com/VegaPublish/vega/issues/114 and here https://github.com/VegaPublish/vega/issues/162

When those two issues are wrapped up, this issue should be superseded by a more detailed spec of what's left.

**Comment by bjoerge** [comment]
Not sure if ther's anything actionable left here. WDYT @kristofferj?
