### ISSUE TITLE
Implement vega specific FormField and Fieldset components

### ISSUE THREAD

**Issue by bjoerge** [VegaPublish/vega#114]
After #97, I think the best way to proceed is to override the default FormField and Fieldset components to render custom markers and menus for copying pointer paths to clipboard.

**Comment by thomax** [comment]
Issue in Sanity https://github.com/sanity-io/sanity/issues/617

**Comment by thomax** [comment]
A first pass at this has now been pushed to the master branch. Closing.

**Comment by thomax** [comment]
Not quite done, it seems. We want to paste different data depending on destination.0

**Comment by thomax** [comment]
New issues appearing downstream from this: https://github.com/VegaPublish/vega/issues/162
