### ISSUE TITLE
Development Ready Lyra 

### ISSUE THREAD

**Issue by simen** [VegaPublish/vega#144]
A Lyra version that we can run Vega against

**Comment by rexxars** [comment]
To run Vega against your locally running Lyra, you can put the following in your Vega `sanity.json` file:

```js
{
  // ...
  "api": {
    "apiHost": "http://localhost:4000",
    "useProjectHostname": false,
    "projectId": "vega",
    "dataset": "vega"
  }
}
```

Obviously there are a lot of things that is not working currently, but serves as a starting point
