### ISSUE TITLE
End to end verify functionality as per December, needs #39

### ISSUE THREAD

**Issue by simen** [VegaPublish/vega#16]
File or fix issues as needed.

**Comment by simen** [comment]
Some issues I found. Some we should address immediately, some we should promote to separate issues. Discuss:

Omissions
* [ ] New Issue view is broken and has no comment bar
* [ ] Go to edit article from an article summary
* [ ] Edit article does not work (I can't edit)
* [ ] Comment replies are not threaded
* [ ] Created issue, but not in list
* [ ] Can't get to edit issue from issues view
* [ ] Comment thingie complains about missing "patchChannel" all the time
* [ ] Does "Appears in issue" work? Does flash, link not working
* [ ] Comment column should clear immediately when context changes

Features
* [ ] Comment column should show context
* [ ] Development grid should update when an article changes state
* [ ] Needs to be a way to create a new issue in issue and development view
* [ ] Hide track field from users that are not editors
* [ ] After expanding (and collapsing another) issue, should make sure issue is in view
* [ ] Should hide "Appears in issues" when in issues view
* [ ] Should say "Appears in issue" in the 99.9999% of instances where it appears in only one issue

Concerns
* [ ] Because of validation, we should keep "publish" semantics, but find a better name for it. "Store", "Effectuate" …

**Comment by thomax** [comment]
I've moved the remaining non-communicator items from this list over to https://github.com/VegaPublish/vega/issues/67

Closing this.
