### ISSUE TITLE
Scrolling in the communication/conversation sidebar

### ISSUE THREAD

**Issue by kristofferj** [VegaPublish/vega#164]

**Comment by bjoerge** [comment]
The development is currently being done in the `feature/comment-editor` branch

**Comment by kristofferj** [comment]
This is mostly complete, but the comments and content needs styling to. And a merge to master.

**Comment by bjoerge** [comment]
Can this be closed now?

**Comment by kristofferj** [comment]
After testing this it doesnt seem that it scrolls down when commenting or a new comment appear.

**Comment by bjoerge** [comment]
>After testing this it doesnt seem that it scrolls down when commenting or a new comment appear.

Tracked in #186
