### ISSUE TITLE
Restrict editing of comments

### ISSUE THREAD

**Issue by bjoerge** [VegaPublish/vega#183]
Currently all logged in users can edit each others comments. We need to figure out what the rules are wrt. permissions and comment editing, and how these rules should be implemented & enforced.

**Comment by simen** [comment]
When the Lyra™ Security System is in place, we can start implementing the actual access rules. I was thinking users only had the ability to create/update comments where they were set as owners.

**Comment by thomax** [comment]
Disableing the comment field in Studio only requires a 5 min fix. Setting up Saga rules requires a 1 hour fix (tests etc).

**Comment by bjoerge** [comment]
@simen, @thomax What's the status here?
