### ISSUE TITLE
Reading focused comment from URL

### ISSUE THREAD

**Issue by bjoerge** [VegaPublish/vega#187]
For #186, to be able to link to a given comment/reply we need to read the comment ID from the url.

I suggest we leave it up to each tool to determine how to get the comment id from the url, and pass it as a prop to the communicator which then takes care of the rest.

**Comment by thomax** [comment]
- [x] issues tool
 - [x] tracks tool
 - [ ] composer tool

**Comment by bjoerge** [comment]
I think what remains here is just the scroll logic / fixing scroll position of focused element while loading I'll take a stab on that a bit later on.
