### ISSUE TITLE
Blank screen on Issue delete

### ISSUE THREAD

**Issue by ghukill** [VegaPublish/vega#2]
Seeing this error in console on deleting Issue, with blank gray screen on GUI:

![Screen Shot 2019-03-21 at 11 19 59 AM](https://user-images.githubusercontent.com/1753087/54762935-70894780-4bcb-11e9-9cf5-2dff52507185.png)

**Comment by ghukill** [comment]
Still exists on Lyra client v0.3

**Comment by s2ceball** [comment]
Resolved.
