### ISSUE TITLE
Author mode

### ISSUE THREAD

**Issue by simen** [VegaPublish/vega#20]
Article state view, also available to editors from a special link from article summaries.

**Comment by thomax** [comment]
We probably need a quick bikeshed on this one? What does this UI look/feel like and what's the best and quickest way (technically) to achieve this.

How are authors granted access to this interface? Exactly what can the author do and see when `article.stage` prohibits author editing?

**Comment by thomax** [comment]
Waiting for https://github.com/VegaPublish/vega/issues/76

**Comment by thomax** [comment]
An editor creates an article, with correct track+stage, and proceeds to invite an email address (or existing user) to become a submitter. We need a component for adding a (non-existing) user from the article view.

In the Composer tool, put each article field inside a correctly configured `<RequireCapability />` component.

**Comment by thomax** [comment]
First version of working author-mode is now in the master branch. This feature also includes a pattern for exposing certain fields (for edit) only to users with the correct roles.
