### ISSUE TITLE
Design / implement: Custom auth/login for Vega

### ISSUE THREAD

**Issue by simen** [VegaPublish/vega#27]
Think through how users etc work. Implement security rules.

**Comment by thomax** [comment]
I'm doing a first pass at this now. Both to get a feel for pain points, and in order to support an upcoming Vega workshop.

**Comment by thomax** [comment]
Need a way to render providers based on dataset. Will be solved by https://github.com/sanity-io/sanity-priv/issues/267#issuecomment-386264269

**Comment by thomax** [comment]
https://github.com/sanity-io/sanity/pull/793

**Comment by thomax** [comment]
Done. I just went ahead and deployed Vega with a prerelease version of Sanity.
