### ISSUE TITLE
Migrate Warded component

### ISSUE THREAD

**Issue by bjoerge** [VegaPublish/vega#45]
Could we maybe also consider a better name? E.g. `<RequireRole>` or something?

**Comment by thomax** [comment]
Agreed. Looks like this task is next on my list.

**Comment by thomax** [comment]
Or rather `<RequireCapability>`, because capability is derived from the context of user role & the document the user wants to edit.

**Comment by thomax** [comment]
Done. `roleStore` is now a part which is used by the `RequireCapability` component.
