### ISSUE TITLE
Edit issue without draft mode

### ISSUE THREAD

**Issue by bjoerge** [VegaPublish/vega#57]
In order to support this in desk tool we need either 1) a way to turn of draft mode for certain document types, or 2) to expose EditorWrapper from desk-tool, and support a `prop` for toggling draft mode.

**Comment by simen** [comment]
I feel we should make it possible to turn off daft-support / "publish" for certain document types in the schema. What do you think @evenwestvang? `drafts: false`?

**Comment by thomax** [comment]
This has been solved in https://github.com/sanity-io/sanity/pull/741 (`liveEdit: true`).
