### ISSUE TITLE
Configurable Publish-button screen text (it can't be "Publish")

### ISSUE THREAD

**Issue by bjoerge** [VegaPublish/vega#58]
Needs to be specified further

**Comment by thomax** [comment]
Or "store" or "effectuate" or somesuch?

Fixing this should probably wait until https://github.com/VegaPublish/vega/issues/57 has been resolved.

**Comment by thomax** [comment]
"confirm"?

**Comment by bjoerge** [comment]
Can this be closed now that we have `liveEdit: true` ?

**Comment by thomax** [comment]
> Can this be closed now that we have liveEdit: true ?

Nope, sorry about the unclear wording. This issue is about changing the screen text on the Publish button.

**Comment by bjoerge** [comment]
I see, that means we still want to have the _edit -> publish_ workflow on some schema types?

**Comment by thomax** [comment]
That's a pretty good question, not sure I have the answer to that one :)
