### ISSUE TITLE
Styling bugs roundup

### ISSUE THREAD

**Issue by thomax** [VegaPublish/vega#75]
- [x] Consistent UI regarding the left-hand green border on selected stuff (IssuesTool and TracksTool renders this differently)
- [x] IssuesTool: Scrolling doesn't work properly when selecting another issue
- [ ] IssuesList: When one article is selected, all other articles are _very_ grayed out. Is this correct?

**Comment by kristofferj** [comment]
Consistent UI is a new issue now. #170

**Comment by kristofferj** [comment]
issuestList: Yes this is correct. It's function is to highlight the current selected
