### ISSUE TITLE
Footnotes input jumps around the screen

### ISSUE THREAD

**Issue by thomax** [VegaPublish/vega#91]
https://sanity-io.slack.com/files/U02ACPTK2/FAP94LR7U/wayne-state_-_sanity_-_google_chrome_5_1_2018_1_46_55_pm_2_.mp4

**Comment by thomax** [comment]
This is still an issue. Placement of footnote input seems to be dependent on width of footnote text.

**Comment by kristofferj** [comment]
This should be fixed in the latest next branch in sanity

**Comment by kristofferj** [comment]
The "click to edit" issue will be solved with a new version of the block editor
