### ISSUE TITLE
Width jitter

### ISSUE THREAD

**Issue by thomax** [VegaPublish/vega#92]
https://sanity-io.slack.com/files/U02ACPTK2/FANHK3D7B/wayne-state_-_sanity_-_google_chrome_5_1_2018_1_46_55_pm.mp4

**Comment by thomax** [comment]
Can't reproduce anymore. Waiting for confirmation from Molly/Bonnie.

**Comment by kristofferj** [comment]
Is this still an issue? I think it is connected to the closed footnote issue. Cant reproduce locally

**Comment by bjoerge** [comment]
Haven't seen this issue in a while, so closing.
